### ISSUE TITLE
关于与友盟的集成

### ISSUE THREAD

**Issue by wanglang** [50431040/package_by_walle#1]
友盟的集成预初始化需要在原生代码中调用，但是android的原生代码MainActivity无法引用到walle的包和方法，请问如何解决呢？

**Comment by 50431040** [comment]
>

**Comment by 50431040** [comment]
> 友盟的集成预初始化需要在原生代码中调用，但是android的原生代码MainActivity无法引用到walle的包和方法，请问如何解决呢？

友盟的初始化必须在MainActivity中调用吗？不是的话可以使用methodChannel

**Comment by 50431040** [comment]
> 友盟的集成预初始化需要在原生代码中调用，但是android的原生代码MainActivity无法引用到walle的包和方法，请问如何解决呢？

你可以看下实现的源码，在我的博客上面，对应复制进去就好了，不懂的话可以问我
