### ISSUE TITLE
执行多渠道打包命令失败

### ISSUE THREAD

**Issue by a1239897580** [50431040/package_by_walle#2]

**Comment by a1239897580** [comment]
![image](https://user-images.githubusercontent.com/70512922/170240571-c7c5e6c3-a1ad-4c06-bcbf-179061f06e6c.png)

**Comment by a1239897580** [comment]
我尝试了插件下的示例项目也不行

**Comment by a1239897580** [comment]
![image](https://user-images.githubusercontent.com/70512922/170240842-184b7fb5-cd22-430d-806f-7f3da5f16ebb.png)

**Comment by 50431040** [comment]
> 我尝试了插件下的示例项目也不行

我搜了下是jdk版本对不上，你尝试改一下ide配置呢

**Comment by a1239897580** [comment]
怎么修改，具体是改哪一个可以截图一下吗

**Comment by 50431040** [comment]
> 怎么修改，具体是改哪一个可以截图一下吗

Preferences -> Build,Execution -> Build Tools -> Gradle -> Gradle JDK
尝试降低版本，我这边是11
